workflows:
  ios-simulator-workflow:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS Simulator (Debug)
        script: |
          flutter build ios --simulator --debug

    artifacts:
      - build/ios/iphonesimulator/Runner.app
